### ISSUE TITLE
More informative warning after trigger capsule failure

### ISSUE THREAD

**Issue by tmchartrand** [AllenNeuralDynamics/aind-data-transfer#159]
**Is your feature request related to a problem? Please describe.**
My upload job failed when trying to trigger a generic capsule run, likely because of insufficient permissions from my Code Ocean API key (?). However, the failure gives the following uninformative stack trace (from an attempt to load the empty post response as json):
```
Traceback (most recent call last):
  File "/local1/storage/envs/cloud_admin/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/local1/storage/envs/cloud_admin/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tom.chartrand/work/aind-data-transfer/src/aind_data_transfer/jobs/s3_upload_job.py", line 443, in <module>
    job.run_job()
  File "/home/tom.chartrand/work/aind-data-transfer/src/aind_data_transfer/jobs/s3_upload_job.py", line 333, in run_job
    self.trigger_codeocean_capsule()
  File "/home/tom.chartrand/work/aind-data-transfer/src/aind_data_transfer/jobs/s3_upload_job.py", line 228, in trigger_codeocean_capsule
    logging.debug(f"Run response: {run_response.json()}")
  File "/local1/storage/envs/cloud_admin/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Describe the solution you'd like**
Ideally the code ocean API could track down the failure and report in detail if its due to permissions (maybe this belongs in that repo?). Alternatively, a simple check for an empty response and providing a generic error would at least be better than nothing.

**Describe alternatives you've considered**

**Additional context**

**Comment by mekhlakapoor** [comment]
Closing because we will not work on this issue as we move towards airflow.
